services:
  db:
    image: postgres:15
    profiles: [ "legacy-postgres" ]
    ports:
    - "5434:5432"
    environment:
      POSTGRES_USER: invented_tales
      POSTGRES_PASSWORD: local
      POSTGRES_DB: little_stories_development
    volumes:
      - db_data:/var/lib/postgresql/data

  worker_db:
    profiles: [ "legacy-postgres" ]
    ports:
    - "5433:5432"
    image: postgres:15
    environment:
      POSTGRES_USER: worker
      POSTGRES_PASSWORD: worker
      POSTGRES_DB: worker_db
    volumes:
      - worker_db_data:/var/lib/postgresql/data

  test_db:
    image: postgres:15
    profiles: [ "legacy-postgres" ]
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: invented_tales
      POSTGRES_PASSWORD: local
      POSTGRES_DB: little_stories_test
    volumes:
      - test_db_data:/var/lib/postgresql/data

  test_worker_db:
    profiles: [ "legacy-postgres" ]
    ports:
      - "5436:5432"
    image: postgres:15
    environment:
      POSTGRES_USER: worker
      POSTGRES_PASSWORD: worker
      POSTGRES_DB: test_worker_db
    volumes:
      - test_worker_db_data:/var/lib/postgresql/data

volumes:
  db_data:
  worker_db_data:
  test_db_data:
  test_worker_db_data:
